const cars = [
    {
        image: "https://pngimg.com/d/honda_PNG10325.png",
        seats: 5,
        fuelType: "petrol",
        transmissionType: "automatic",
        price: 250,
        carType: "race",
        isOnSale: false,
    },
    {
        image: "https://pngimg.com/d/lamborghini_PNG10702.png",
        seats: 5,
        fuelType: "petrol",
        transmissionType: "automatic",
        price: 1300,
        isOnSale: true,
        oldPrice: 1300,
        carType: "race",
        newPrice: 1200,
    },
    {
        image: "https://freepngimg.com/save/58064-utility-sport-car-2018-m40i-vehicle-x3/1712x948",
        seats: 7,
        fuelType: "diesel",
        transmissionType: "automatic",
        price: 250,
        isOnSale: true,
        oldPrice: 200,
        carType: "luxury",
        newPrice: 100,
    },
    {
        image: "https://i.pinimg.com/originals/dc/19/e9/dc19e9b94a372ebc21ffeb7623d5632a.png",
        seats: 5,
        fuelType: "diesel",
        transmissionType: "automatic",
        price: 450,
        carType: "family",
        isOnSale: false,
    },
    {
        image: "https://i.pinimg.com/originals/5d/4d/b6/5d4db6e517a689e87c4266f61d77f803.png",
        seats: 5,
        fuelType: "petrol",
        transmissionType: "manual",
        isOnSale: true,
        price: 350,
        oldPrice: 350,
        carType: "small",
        newPrice: 200,
    },
    {
        image: "https://www.freeiconspng.com/thumbs/car-png/volkswagen-car-png-image-7.png",
        seats: 7,
        fuelType: "diesel",
        transmissionType: "automatic",
        price: 250,
        isOnSale: true,
        oldPrice: 200,
        carType: "small",
        newPrice: 100,
    },
    {
        image: "https://www.picng.com/upload/audi/png_audi_19103.png",
        seats: 2,
        fuelType: "petrol",
        transmissionType: "automatic",
        price: 160,
        carType: "suv",
        isOnSale: false,
    },
    {
        image: "https://www.pngmart.com/files/22/Audi-TT-PNG.png",
        seats: 2,
        fuelType: "petrol",
        transmissionType: "manual",
        isOnSale: true,
        price: 350,
        oldPrice: 500,
        carType: "race",
        newPrice: 100,
    },
    {
        image: "https://www.pngmart.com/files/22/BMW-X7-Download-PNG-Image.png",
        seats: 7,
        fuelType: "diesel",
        transmissionType: "automatic",
        price: 550,
        isOnSale: false,
        carType: "family",
    },
];

module.exports = {
    cars,
};
